name: Deploy to developer

on:
  push:
    branches:
      - developer
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v6

      - name: 'Login to ACR'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}
